services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_REGION: us-east-1
      MINIO_BROWSER_REDIRECT_URL: http://localhost:9001
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hive
      - POSTGRES_DB=metastore_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # The Hive Metastore service
  hive-metastore:
    image: apache/hive:4.0.0-beta-1 # Use Hive 4.0.0+ for direct Iceberg compatibility
    container_name: metastore
    restart: always
    environment:
      - SERVICE_NAME=hive-metastore
      - HIVE_CUSTOM_CONF_DIR=/opt/hive-conf
      - DOCKER_HOST_IP=host.docker.internal # Allows access from the host network
      - DATABASE_VENDOR=postgres
      - DATABASE_NAME=metastore_db
      - DATABASE_USER=hive
      - DATABASE_PASSWORD=hivepassword
      - DATABASE_URL=jdbc:postgresql://postgres:5432/metastore_db
      - METASTORE_CONNECTION_URL=jdbc:postgresql://postgres:5432/metastore_db
      - METASTORE_DB_DRIVER=org.postgresql.Driver
    ports:
      - "9083:9083"
    volumes:
      # Mount the hive-conf directory
      - ./docker/hive-site.xml:/opt/hive-conf/hive-site.xml
    depends_on:
      - postgres

volumes:
  postgres:
  postgres_data:
  minio_data:
    driver: local 