services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_REGION: us-east-1
      MINIO_BROWSER_REDIRECT_URL: http://localhost:9001
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  postgres:
    # version should be lower postgres 10.x
    image: postgres:9.6.24
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hivepassword
    command: >
      postgres -c config_file=/var/lib/postgresql/data/postgresql.conf

  hive-metastore:
    image: apache/hive:3.1.3
    container_name: hive-metastore
    ports:
      - "9083:9083"  # Hive Metastore port
      - "10000:10000"  # beeline
    environment:
      DB_DRIVER: postgres
      SERVICE_NAME: metastore
      HIVE_DB: metastore
      HIVE_USER: hive
      HIVE_PASSWORD: hivepassword
      HIVE_DB_HOST: postgres
      HIVE_DB_PORT: 5432
      HIVE_LOG_LEVEL: DEBUG
#    entrypoint: >
#      sh -c "
#      mkdir -p /tmp/hive/ &&
#      chmod -R 755 /tmp/hive/ &&
#      cd /home
#      mkdir -p hive
#      chmod -R 755 /home/hive/ &&
#      /opt/hive/bin/schematool -dbType postgres -initSchema --verbose &&
#      /opt/hive/bin/hive --service metastore"
    entrypoint: >
      sh -c "
      mkdir -p /tmp/hive/ &&
      chmod -R 755 /tmp/hive/ &&
      cd /home
      mkdir -p hive
      chmod -R 755 /home/hive/ &&
      /opt/hive/bin/hive --service metastore"
    volumes:
      - ./scripts/hive-site.xml:/opt/hive/conf/hive-site.xml
      - ./scripts/hive-lib/aws-java-sdk-bundle-1.11.1026.jar:/opt/hive/lib/aws-java-sdk-bundle-1.11.1026.jar
      - ./scripts/hive-lib/hadoop-aws-3.3.4.jar:/opt/hive/lib/hadoop-aws-3.3.4.jar
#    healthcheck:
#      test: ["CMD", "nc", "-z", "localhost", "9083"]
#      interval: 30s
#      timeout: 20s
#      retries: 3

volumes:
  postgres:
  hive-tmp:
  minio_data:
    driver: local 