services:
  # MinIO for local S3-compatible storage
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_REGION: us-east-1
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always

  # MinIO Client for setup (bucket creation and policies)
  minio-client:
    image: minio/mc:latest
    container_name: minio-client-airflow
    depends_on:
      - minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_REGION: us-east-1
      STORAGE_ENDPOINT: http://minio:9000
    entrypoint: [ "sh", "-c", "/scripts/minio-init.sh" ]
    volumes:
      - ./docker/minio-init.sh:/scripts/minio-init.sh
      - ./src/main/resources/parquet:/examples/parquet

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hive
      - POSTGRES_DB=metastore_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # The Hive Metastore service
  hive-metastore:
    build:
      context: .
      dockerfile: Dockerfile.hive4
    container_name: hive-metastore
    restart: always
    environment:
      - SERVICE_NAME=metastore
      - HIVE_CUSTOM_CONF_DIR=/opt/hive-conf
      - DOCKER_HOST_IP=host.docker.internal # Allows access from the host network
      - DB_DRIVER=postgres
      - DATABASE_VENDOR=postgres
      - DATABASE_NAME=metastore_db
      - DATABASE_USER=hive
      - DATABASE_PASSWORD=hive
      - DATABASE_URL=jdbc:postgresql://postgres:5432/metastore_db
      - METASTORE_CONNECTION_URL=jdbc:postgresql://postgres:5432/metastore_db
      - METASTORE_DB_DRIVER=org.postgresql.Driver
    ports:
      - "9083:9083"
    depends_on:
      - postgres

volumes:
  postgres:
  postgres_data:
  minio_data:
    driver: local 